namespace AdofaiMapConverter.Types
{
    public enum HitSound
    {
        Hat,
        Kick,
        Shaker,
        Sizzle,
        Chuck,
        ShakerLoud,
        None,
        Hammer,
        KickChroma,
        SnareAcoustic2,
        Sidestick,
        Stick,
        ReverbClack,
        Squareshot,
        PowerDown,
        PowerUp,
        KickHouse,
        KickRupture,
        HatHouse,
        SnareHouse,
        SnareVapor,
        ClapHit,
        ClapHitEcho,
        ReverbClap,
        FireTile,
        IceTile,
        VehiclePositive,
        VehicleNegative
    }
}
